Replace step with code

diff --git a/.github/workflows/check-eol.yml b/.github/workflows/check-eol.yml
--- a/.github/workflows/check-eol.yml
+++ b/.github/workflows/check-eol.yml
@@ -30,6 +30,22 @@ jobs:
           ref: ${{ inputs.ref }}
 
       - name: Check End-of-Line Sequences
-        uses: Arthri/check-eol-composite@v1
-        with:
-          default-eol: ${{ inputs.default-eol }}
+        env:
+          DEFAULT_EOL: ${{ inputs.default-eol }}
+        run: |
+          exit_code=0
+
+          while IFS= read line; do
+            if [[ $line =~ ^i/([^ ]*)\ +w/[^\ ]*\ +attr/[^$'\t']+$'\t'(.+)$ ]] ; then
+              index_eol=${BASH_REMATCH[1]}
+              if [ "$index_eol" != $DEFAULT_EOL ] && [ "$index_eol" != 'none' ] && [ "$index_eol" != '-text' ] && [ "$index_eol" != '' ] ; then
+                echo "${BASH_REMATCH[2]}:"$'\t'"End-of-line sequence in index($index_eol) must be LF."
+                exit_code=1
+              fi
+            else
+              echo 'Unable to match '"$line"
+              exit_code=1
+            fi
+          done < <(git ls-files --eol)
+
+          exit $exit_code
